name: 'Continuous Delivery'

on:
  push:
    branches:
      - feature/deploy

env:
  PROJECT_ID: latam-challenge-448714
#   GAR_LOCATION: YOUR_GAR_LOCATION # TODO: update Artifact Registry location
#   REGION: YOUR_APP_REGION # TODO: update Cloud Run service region
#   APP: app

jobs:
  deploy:
    # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
        - uses: 'actions/checkout@v4'

        - uses: 'google-github-actions/auth@v2'
          with:
            project_id: '${{ env.PROJECT_ID }}'
            workload_identity_provider: 'projects/831127518569/locations/global/workloadIdentityPools/github/providers/my-repo'

      # - name: 'Set up Cloud SDK'
      #   uses: 'google-github-actions/setup-gcloud@v1'
      #   with:
      #     project_id: '${{ env.PROJECT_ID }}'

      # - name: 'Docker auth'
      #   run: |-
      #     gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev

      # - name: 'Build and push container'
      #   run: |-
      #     docker build -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.APP }}/${{ env.APP }}:${{ github.sha }}" ./app
      #     docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.APP }}/${{ env.APP }}:${{ github.sha }}"
